remote_theme: rundocs/jekyll-rtd-theme
.. toctree::
Basic electrical requirements
Unboxing
Preliminary checks
Creating a SlushPool account
Initial startup
Miner configuration
Connecting to SlushPool
Setting up the BlackBox (coming soon)
DIY BlackBox instructions (coming soon)
Advanced Topics, Mining with a VPN & Test Networks/Firmware (coming soon)
